lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
    url(r'^new$',views.new_list,name='new_list'),
    url(r'^(\d+)/$',views.view_list,name='view_list'),
    url(r'^(\d+)/add_item$',views.add_item,name='add_item'),
]

superlists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
    url(r'^$', views.home_page,name='home'),
    url(r'^lists/new$',views.new_list,name='new_list'),
    url(r'^lists/(\d+)/$',views.view_list,name='view_list'),
    url(r'^lists/(\d+)/add_item$',views.add_item,name='add_item'),
]

lists/models.py
from django.db import models

class List(models.Model):
    pass

class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List,on_delete=models.CASCADE,default=None)

lists/views.py
from django.http import HttpResponse
from django.shortcuts import redirect,render
from lists.models import Item,List

def home_page(request):
    """
    if request.method == 'POST':
        Item.objects.create(text=request.POST['item_text'])
        return redirect('/lists/the-only-list-in-the-world/')
    return render(request,'home.html')
    """
    return render(request,'home.html')
def view_list(request,list_id):
    list_ = List.objects.get(id=list_id)
#    items = Item.objects.filter(list=list_)
    return render(request,'list.html',{'list':list_})
def new_list(request):
    list_=List.objects.create()
    Item.objects.create(text=request.POST['item_text'],list=list_)
    return redirect(f'/lists/{list_.id}/')

def add_item(request,list_id):
    list_ = List.objects.get(id=list_id)
    Item.objects.create(text=request.POST['item_text'],list=list_)
    return redirect(f'/lists/{list_.id}/')

lists/templates/home.html
{% extends 'base.html' %}
{% block header_text %}Start a new To-Do list{% endblock %}
{% block form_action %}/lists/new{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}
{% block header_text %}Your To-Do list{% endblock %}
{% block form_action %}/lists/{{list.id}}/add_item{% endblock %}		
{% block table %}	
	<table id="id_list_table">
		{% for item in list.item_set.all %}
			<tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
		{% endfor %}
	</table>
{% endblock %}